version: '3.4'

services:
  DecompNumberAPI:
    container_name: DecompNumberAPI
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8001:80

  DecompNumberMinimalAPI:
    container_name: DecompNumberMinimalAPI
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8002:80